Removed `toolchain` flag since it breaks builds in travis
TODO: Need to figure out why `toolchain=gcc` works local, but breaks on travis
with:

> error: "toolset=gcc" is not an implicit feature value

in build: https://travis-ci.com/jackson15j/cpp_random_projects_for_learning/builds/81251814